<?php

namespace GDSS\PhasesBundle\Repository;

/**
 * CompIdeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompIdeaRepository extends \Doctrine\ORM\EntityRepository
{
}
