<?php

namespace GDSS\PhasesBundle\Repository;

/**
 * BrainstormingContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenerationContributionRepository extends \Doctrine\ORM\EntityRepository
{
}
