<?php

namespace GDSS\PhasesBundle\Repository;

/**
 * GenerationSubSubjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenerationSubSubjectRepository extends \Doctrine\ORM\EntityRepository
{
}
