<?php

namespace GDSS\PhasesBundle\Repository;

/**
 * BrainstormingCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenerationCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
