<?php

namespace GDSS\PhasesBundle\Repository;

/**
 * GenerationCommentReplyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenerationCommentReplyRepository extends \Doctrine\ORM\EntityRepository
{
}
