<?php

namespace GDSS\PhasesBundle\Repository;

/**
 * GenerationSubSubjectContributionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenerationSubSubjectContributionRepository extends \Doctrine\ORM\EntityRepository
{
}
