<?php

namespace GDSS\PhasesBundle\Repository;

/**
 * MakersGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MakersGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
