<?php

namespace GDSS\PhasesBundle\Repository;

/**
 * NegociationCategorieSelectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NegociationCategorieSelectionRepository extends \Doctrine\ORM\EntityRepository
{
}
