<?php

namespace GDSS\PhasesBundle\Repository;

/**
 * NegociationCategoriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NegociationCategoriesRepository extends \Doctrine\ORM\EntityRepository
{
}
