<?php

namespace GDSS\PhasesBundle\Repository;

/**
 * NegociationFormVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NegociationFormVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
