<?php

namespace GDSS\PhasesBundle\Repository;

/**
 * ReactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReactionRepository extends \Doctrine\ORM\EntityRepository
{
}
