<?php

namespace GDSS\PlatformBundle\Repository;

/**
 * ConstraintsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConstraintsRepository extends \Doctrine\ORM\EntityRepository
{
}
