<?php

namespace GDSS\PlatformBundle\Repository;

/**
 * ContraintesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContraintesRepository extends \Doctrine\ORM\EntityRepository
{
}
