<?php

namespace GDSS\PlatformBundle\Repository;

/**
 * CriteresRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriteresRepository extends \Doctrine\ORM\EntityRepository
{
}
