<?php

namespace GDSS\PlatformBundle\Repository;

/**
 * CriteriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CriteriaRepository extends \Doctrine\ORM\EntityRepository
{
}
