<?php

namespace GDSS\PlatformBundle\Repository;

/**
 * DecideursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecideursRepository extends \Doctrine\ORM\EntityRepository
{
}
