<?php

namespace GDSS\PlatformBundle\Repository;

/**
 * DecisionMakersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DecisionMakersRepository extends \Doctrine\ORM\EntityRepository
{
}
