<?php

namespace GDSS\PlatformBundle\Repository;

/**
 * PhasesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhasesRepository extends \Doctrine\ORM\EntityRepository
{
}
