<?php

namespace GDSS\PlatformBundle\Repository;

/**
 * ProcessusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProcessusRepository extends \Doctrine\ORM\EntityRepository
{
}
