<?php

namespace GDSS\PlatformBundle\Repository;

/**
 * RepertoireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RepertoireRepository extends \Doctrine\ORM\EntityRepository
{
}
