services:
#    gdss_platform.example:
#        class: GDSS\PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    acme_user.activity_listener:
            class: GDSS\PlatformBundle\EventListener\ActivityListener
            arguments: ['@security.token_storage', '@fos_user.user_manager']
            tags:
                - { name: kernel.event_listener, event: kernel.controller, method: onCoreController }
    platform.progress:
        class: GDSS\PlatformBundle\Services\Progress

    platform.checkaccess:
        class: GDSS\PlatformBundle\Services\CheckAccess
        arguments: ["@doctrine.orm.entity_manager"]

    problemdata:
        class: GDSS\PlatformBundle\Services\problemdata
        arguments: ["@doctrine.orm.entity_manager"]

    getconstraintsthinklets:
            class: GDSS\PlatformBundle\Services\GetConstraintsThinklets
            arguments: ["@doctrine.orm.entity_manager"]

    platform.sendmsg:
        class: GDSS\PlatformBundle\Services\SendMessage
        arguments: ["@doctrine.orm.entity_manager", "@fos_message.composer", "@fos_message.sender"]