services:
#    gdss_phases.example:
#        class: GDSS\PhasesBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    timer:
        class : GDSS\PhasesBundle\Services\Timer

    leafhopper:
        class: GDSS\PhasesBundle\Services\Leafhopper
        arguments: ["@doctrine.orm.entity_manager"]

    percentage:
        class: GDSS\PhasesBundle\Services\percentage
        arguments: ["@doctrine.orm.entity_manager"]